/* FCU_READY_BOOTSTRAP */
Promise.resolve(window.FCU_READY).then(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const num=n=>Number(n||0).toLocaleString('pt-BR',{maximumFractionDigits:2}),int=n=>Number(n||0).toLocaleString('pt-BR'),pct=n=>(n*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const palette=['#087a61','#97cf35','#ed6681','#d6dee5'];
let book=window.FCU_INITIAL,original=window.FCU_ORIGINAL,selected=0,baseIndex=0,base=[],filtered=[],page=0,sortCol=-1,sortDir=1,tableRows=[],tableHeaders=[],tableRaw=false;
let matchedProjects=new Set(),sourceToken=window.FCU_INITIAL.name+'|'+window.FCU_INITIAL.reference,originalToken=sourceToken;
const dims={project:['Projeto_Tratado','Projeto'],contractor:['Empreiteira_Contratos','Empreiteira'],region:['polo','Polo'],intervention:['Tipo_Int','Tipo_Intervenção'],status:['Status_Programação_Tratado','Status_Sigeo'],critical:['Criticidade'],date:['Data_Programação_Tratada','Data_Programação','Data Prog','Data_Programacao'],reason:['Motivo_Agrupado','Agrupamento','motivo_canc_exec_parcial'],order:['Ordem_Sigeo','Ordem_SIGEO']};
const filterIds=['contractor','region','intervention','status','critical'];
const sheetLabels={'00_Capa':'Capa e conteúdo','01_Base_Original':'Base original','02_Base_Tratada':'Base tratada','03_Resumo_Projetos':'Resumo por projeto','04_Historico_Projetos':'Histórico de projetos','05_Cancelamentos':'Cancelamentos','06_Motivos':'Motivos','07_Empreiteiras':'Contratadas','08_Polos':'Polos','09_Tipo_Intervencao':'Intervenções','10_Projetos_Criticos':'Projetos críticos','11_Pendentes':'Pendentes','12_Qualidade_Dados':'Qualidade dos dados','13_Dashboard':'Dashboard original','Apoio Dashboard':'Apoio ao dashboard'};
function field(headers,keys){for(const k of keys){const i=headers.findIndex(h=>norm(h)===norm(k));if(i>=0)return i}return -1}
function dateISO(v){if(v===null||v===undefined||v==='')return '';if(typeof v==='number'&&v>10000&&v<100000)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const s=String(v),iso=s.match(/^(\d{4})-(\d{2})-(\d{2})/),br=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);let y,m,d;if(iso)[,y,m,d]=iso;else if(br)[,d,m,y]=br;else return '';const out=`${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`;const dt=new Date(out+'T12:00:00Z');return Number.isNaN(+dt)||dt.toISOString().slice(0,10)!==out?'':out}
function display(v,fmt='',header=''){if(v===null||v===undefined||v==='')return '';if(typeof v==='boolean')return v?'SIM':'NÃO';if(typeof v==='number'){if(fmt.includes('%'))return pct(v);if(/hora/i.test(header)||/[hH]:/.test(fmt)){const sec=Math.round(v*86400);return [Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(n=>String(n).padStart(2,'0')).join(':')}if(Number.isInteger(v))return String(v);return v.toLocaleString('pt-BR',{maximumFractionDigits:10})}const s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s)){const d=dateISO(v);return d?d.split('-').reverse().join('/')+(s.includes('T')&&s.slice(11,19)!=='00:00:00'?' '+s.slice(11,19):''):s}return s}
function rowsOf(s){const h=s.rows[s.header]||[];return s.rows.slice(s.header+1).map((r,i)=>({r,i:i+s.header+1})).filter(o=>o.r.some(v=>v!==null&&v!==''))}
function mapped(s){const h=s.rows[s.header]||[],m=Object.fromEntries(Object.entries(dims).map(([k,v])=>[k,field(h,v)]));return rowsOf(s).map(o=>{let obj={...o,search:norm(o.r.join(' ')),sheet:s.name};for(const [k,i]of Object.entries(m))obj[k]=i<0?'':o.r[i]??'';obj.date=dateISO(obj.date);return obj})}
function statusType(s){s=norm(s);if(s.includes('parcial'))return 1;if(s==='executado'||s==='executada')return 0;if(s.includes('cancel'))return 2;return 3}
function filterState(){return Object.fromEntries([...filterIds,'globalSearch','dateFrom','dateTo'].map(id=>[id,$(id).value]))}
function matches(r,f){for(const k of filterIds)if(f[k]&&(String(r[k]||'Não informado')!==f[k]))return false;if(f.dateFrom&&(!r.date||r.date<f.dateFrom))return false;if(f.dateTo&&(!r.date||r.date>f.dateTo))return false;if(f.globalSearch&&!r.search.includes(norm(f.globalSearch)))return false;return true}
function chooseBase(){const preferred=book.sheets.findIndex(s=>s.name==='02_Base_Tratada');if(preferred>=0)return preferred;let best=0,score=-1;book.sheets.forEach((s,i)=>{const h=s.rows[s.header]||[],n=(field(h,dims.project)>=0?100:0)+(field(h,dims.date)>=0?100:0)+(field(h,dims.status)>=0?100:0)+Math.min(s.rows.length/100000,1);if(n>score){best=i;score=n}});return best}
function setup(){baseIndex=chooseBase();base=mapped(book.sheets[baseIndex]);selected=baseIndex;for(const k of filterIds){const vals=[...new Set(base.map(r=>String(r[k]||'Não informado')))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$(k).innerHTML='<option value="">Todos</option>'+vals.map(v=>`<option>${esc(v)}</option>`).join('')}$('sourceName').textContent=book.name;$('reference').textContent='Referência da base: '+(book.reference||'não informada');$('sideSheets').textContent=book.sheets.length+' abas disponíveis';$('footerStats').textContent=book.sheets.length+' abas • '+int(base.length)+' registros na base de indicadores';$('sheetTabs').innerHTML=book.sheets.map((s,i)=>`<button role="tab" class="sheet-tab" id="tab-${i}" aria-selected="${i===selected}" data-sheet="${i}">${esc(sheetLabels[s.name]||s.name)}<small>${int(rowsOf(s).length)}</small></button>`).join('');$('sheetSearch').value='';$('columnValue').value='';$('globalSearch').value='';$('dateFrom').value='';$('dateTo').value='';setSheet(selected);refresh()}
function refresh(){const f=filterState();filtered=base.filter(r=>matches(r,f));matchedProjects=new Set(filtered.map(r=>String(r.project)).filter(Boolean));$('filterSummary').textContent=`${int(filtered.length)} de ${int(base.length)} programações no recorte • Indicadores calculados na aba ${book.sheets[baseIndex].name}.`+(f.dateFrom&&f.dateTo&&f.dateFrom>f.dateTo?' A data inicial é posterior à data final.':'');renderKPIs();renderCharts();page=0;renderTable()}
function renderKPIs(){const canceled=filtered.filter(r=>statusType(r.status)===2).length,crits=new Set(filtered.filter(r=>norm(r.critical)==='alta').map(r=>r.project).filter(Boolean)).size,executed=filtered.filter(r=>statusType(r.status)===0).length,partial=filtered.filter(r=>statusType(r.status)===1).length;const k=[['Projetos no recorte',matchedProjects.size,int(filtered.length)+' programações','▦',''],['Execução integral',executed,pct(filtered.length?executed/filtered.length:0)+' das programações','✓',''],['Programações canceladas',canceled,pct(filtered.length?canceled/filtered.length:0)+' das programações','×','pink'],['Projetos críticos',crits,'Alta criticidade informada na base','!','amber']];$('kpis').innerHTML=k.map(([label,v,sub,icon,cls])=>`<article class="kpi ${cls}"><div class="kpi-label">${label}<span class="kpi-symbol">${icon}</span></div><div class="kpi-value">${int(v)}</div><div class="kpi-sub">${sub}</div><div class="kpi-rule"></div></article>`).join('');let reasons={};filtered.filter(r=>statusType(r.status)===2).forEach(r=>reasons[r.reason||'Não informado']=(reasons[r.reason||'Não informado']||0)+1);const top=Object.entries(reasons).sort((a,b)=>b[1]-a[1])[0];const quality=field(book.sheets[baseIndex].rows[book.sheets[baseIndex].header],['Alerta_Qualidade_Dados']);const alerts=quality<0?0:filtered.filter(r=>r.r[quality]).length;$('insight').innerHTML=filtered.length?`<strong>Foco do acompanhamento</strong> &nbsp; ${top?`${esc(top[0])} representa ${pct(top[1]/canceled)} dos cancelamentos deste recorte.`:'Não há cancelamentos neste recorte.'} ${int(partial)} programações têm execução parcial. ${alerts?`${int(alerts)} registros possuem alertas de qualidade na base.`:''}`:'Nenhum registro corresponde aos filtros selecionados.'}
function renderCharts(){let months={},counts=[0,0,0,0],contractors={},reasons={};for(const r of filtered){let t=statusType(r.status);counts[t]++;if(r.date){const m=r.date.slice(0,7);months[m]??=[0,0,0,0];months[m][t]++}const c=r.contractor||'Não informado';contractors[c]??=[0,0,0,0];contractors[c][t]++;if(t===2){const re=r.reason||'Não informado';reasons[re]=(reasons[re]||0)+1}}
 const entries=Object.entries(months).sort((a,b)=>a[0].localeCompare(b[0])),sum=a=>a.reduce((x,y)=>x+y,0),max=Math.max(...entries.map(([,a])=>sum(a)),1);$('trend').innerHTML=entries.length?entries.map(([m,a])=>`<button class="month" data-month="${m}" title="${m}: ${sum(a)} programações; ${a[0]} executadas, ${a[1]} parciais, ${a[2]} canceladas"><span class="count">${int(sum(a))}</span><span class="stack" style="height:${sum(a)/max*155}px">${a.map((v,i)=>`<i style="height:${v/sum(a)*100}%;background:${palette[i]}"></i>`).join('')}</span><span class="monthlabel">${new Date(m+'-15T12:00:00Z').toLocaleDateString('pt-BR',{month:'short',timeZone:'UTC'}).replace('.','')}/${m.slice(2,4)}</span></button>`).join(''):'<div class="empty">Sem datas válidas no recorte.</div>';$('trend').style.overflowX=entries.length>14?'auto':'';if(entries.length>14)Array.from($('trend').children).forEach(e=>e.style.minWidth='45px');
 let acc=0,gradient=counts.map((v,i)=>{let start=acc;acc+=filtered.length?v/filtered.length*100:0;return `${palette[i]} ${start}% ${acc}%`}).join(',');const ex=filtered.length?counts[0]/filtered.length:0;$('statusChart').innerHTML=`<div class="status-layout"><div class="donut" style="background:${filtered.length?'conic-gradient('+gradient+')':'#e7edeb'}"><div class="donut-center"><strong>${pct(ex)}</strong><span>execução integral</span></div></div><div class="status-key">${['Executadas','Execução parcial','Canceladas','Demais situações'].map((s,i)=>`<div class="key-row"><i style="background:${palette[i]}"></i><span>${s}</span><strong>${int(counts[i])}</strong></div>`).join('')}</div></div><div class="status-foot">Integral + parcial: <strong>${pct(filtered.length?(counts[0]+counts[1])/filtered.length:0)}</strong> · O percentual integral considera apenas “Executado”.</div>`;
 $('contractorChart').innerHTML=Object.entries(contractors).sort((a,b)=>sum(b[1])-sum(a[1])).map(([name,a])=>`<div class="contractor-row" data-contractor="${esc(name)}"><button>${esc(name)}</button><div><div class="stackline">${a.map((v,i)=>`<i style="width:${v/sum(a)*100}%;background:${palette[i]}"></i>`).join('')}</div><small>${int(sum(a))} programações</small></div><div>${pct(a[0]/sum(a))}<small>integral</small></div></div>`).join('')||'<div class="empty">Nenhuma contratada no recorte.</div>';
 const re=Object.entries(reasons).sort((a,b)=>b[1]-a[1]);$('reasonsChart').innerHTML=re.slice(0,5).map(([name,n])=>`<div class="reason"><span title="${esc(name)}">${esc(name)}</span><span class="reason-track"><i style="width:${n/re[0][1]*100}%"></i></span><strong>${int(n)}</strong></div>`).join('')||'<div class="empty">Nenhum cancelamento no recorte.</div>';if(re.length>5)$('reasonsChart').innerHTML+=`<div class="muted">Outros motivos: ${int(re.slice(5).reduce((n,x)=>n+x[1],0))} · Lista completa na aba Motivos.</div>`;
}
function setSheet(i){selected=i;page=0;sortCol=-1;$('sheetSearch').value='';$('columnValue').value='';const s=book.sheets[i];tableRaw=['00_Capa','13_Dashboard','Apoio Dashboard'].includes(s.name);tableHeaders=tableRaw?Array.from({length:Math.max(...s.rows.map(r=>r.length),0)},(_,n)=>ExcelIO.col(n)):(s.rows[s.header]||[]).map((h,n)=>h??'Coluna '+ExcelIO.col(n));$('columnFilter').innerHTML='<option value="">Todas as colunas</option>'+tableHeaders.map((h,n)=>`<option value="${n}">${esc(h)}</option>`).join('');document.querySelectorAll('.sheet-tab').forEach((e,n)=>e.setAttribute('aria-selected',n===i));renderTable()}
function filterSheet(){const s=book.sheets[selected],h=s.rows[s.header]||[],f=filterState(),q=norm($('sheetSearch').value),colQ=norm($('columnValue').value),ci=$('columnFilter').value;const hasGlobal=Object.values(f).some(Boolean);let rows=tableRaw?s.rows.map((r,i)=>({r,i})):rowsOf(s);let scope='Todos os valores e colunas da aba original.';
 if($('applyGlobal').checked&&hasGlobal){const hasDate=field(h,dims.date)>=0,hasProject=field(h,dims.project)>=0;if(!tableRaw&&hasDate&&hasProject){const allowed=new Set(mapped(s).filter(r=>matches(r,f)).map(r=>r.i));rows=rows.filter(r=>allowed.has(r.i));scope='Filtros do painel aplicados aos registros desta aba.'}else if(!tableRaw&&hasProject){const p=field(h,dims.project);rows=rows.filter(r=>matchedProjects.has(String(r.r[p])));scope='Projetos presentes no recorte do painel. Valores consolidados mantêm o histórico completo de cada projeto.'}else scope='Esta aba contém um resumo original. Filtros do painel não recalculam seus valores; use a busca ou o filtro de coluna abaixo.'}
 rows=rows.filter(o=>{if(q&&!norm(o.r.map((v,c)=>display(v,s.formats[ExcelIO.col(c)+(o.i+1)],h[c])).join(' ')).includes(q))return false;if(colQ){const vals=ci===''?o.r:[o.r[Number(ci)]];if(!norm(vals.join(' ')).includes(colQ))return false}return true});if(sortCol>=0)rows.sort((a,b)=>{let x=a.r[sortCol],y=b.r[sortCol];if(x===null||x===undefined)return 1;if(y===null||y===undefined)return -1;return sortDir*(typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),'pt-BR',{numeric:true}))});$('sheetDescription').textContent=s.name+' • '+scope+(s.hidden?' • Aba de apoio originalmente oculta no Excel.':'');return rows}
function renderTable(){tableRows=filterSheet();const size=Number($('pageSize').value),pages=Math.max(1,Math.ceil(tableRows.length/size));page=Math.min(page,pages-1);const s=book.sheets[selected],shown=tableRows.slice(page*size,(page+1)*size);const h=`<thead><tr><th><button disabled>Linha</button></th>${tableHeaders.map((x,i)=>`<th><button data-sort="${i}">${esc(x)} ${sortCol===i?(sortDir===1?'↑':'↓'):'↕'}</button></th>`).join('')}</tr></thead>`;
 $('tableWrap').innerHTML=shown.length?`<table class="${tableRaw?'original-grid':''}">${h}<tbody>${shown.map(o=>`<tr><td>${o.i+1}</td>${tableHeaders.map((header,c)=>{const v=o.r[c],formatted=display(v,s.formats[ExcelIO.col(c)+(o.i+1)],header),n=norm(v),isProject=norm(header).startsWith('projeto')&&formatted;let content=esc(formatted)||'—';if(/status|situacao|criticidade/i.test(norm(header))&&formatted){const cls=n.includes('cancel')||n==='alta'?'pink':n.includes('parcial')||n==='media'?'yellow':n==='executado'||n==='concluido'||n==='baixa'?'green':'';content=`<span class="badge ${cls}">${content}</span>`}return `<td class="${!formatted?'cell-empty ':''}${isProject?'project':''}" ${isProject?`tabindex="0" role="button" data-detail="${o.i}"`:''} title="${esc(formatted)}">${content}</td>`}).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhuma linha encontrada. Ajuste os filtros ou a busca nesta aba.</div>';$('tableCount').textContent=int(tableRows.length)+' linhas encontradas • '+tableHeaders.length+' colunas';$('pageInfo').textContent=`${page+1} / ${pages}`;$('prevPage').disabled=page===0;$('nextPage').disabled=page>=pages-1;
}
function detail(index){const s=book.sheets[selected],r=s.rows[index];$('detailTitle').textContent=r[field(tableHeaders,dims.project)]||'Detalhes do registro';$('detailBody').innerHTML='<div class="detail-grid">'+tableHeaders.map((h,c)=>`<div class="detail-cell"><label>${esc(h)}</label><span>${esc(display(r[c],s.formats[ExcelIO.col(c)+(index+1)],h))||'Não informado'}</span></div>`).join('')+'</div>';$('detailDialog').showModal()}
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').style.display='none',4500)}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),20000)}
function base64Bytes(b64){const s=atob(b64),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
function toBase64(buffer){const a=new Uint8Array(buffer),chunk=32768;let s='';for(let i=0;i<a.length;i+=chunk)s+=String.fromCharCode(...a.subarray(i,i+chunk));return btoa(s)}
async function fullExport(){if(original)download(new Blob([base64Bytes(original)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'FCU_Base_Completa.xlsx');else download(await ExcelIO.write(book.sheets),'FCU_Base_Completa.xlsx');toast('Excel completo exportado. Todas as abas preservadas.')}
async function exportQuery(type){const s=book.sheets[selected],rows=[tableHeaders,...tableRows.map(o=>tableHeaders.map((h,c)=>{const v=o.r[c],fmt=s.formats[ExcelIO.col(c)+(o.i+1)];return ((fmt&&(fmt.includes('%')||/[hH]:/.test(fmt)))||/hora/i.test(h))?display(v,fmt,h):v??null}))];if(type==='xlsx')download(await ExcelIO.write([{name:s.name,rows}]),s.name+'_Consulta.xlsx');else {const safe=v=>{let s=String(v??'');if(typeof v==='string'&&/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};download(new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),s.name+'_Consulta.csv')}toast(int(tableRows.length)+' linhas exportadas da aba '+s.name)}
async function db(action,value){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('Sem armazenamento local'));const req=indexedDB.open('fcu-projetos-execucao',1);req.onupgradeneeded=()=>req.result.createObjectStore('base');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const d=req.result,t=d.transaction('base',action==='get'?'readonly':'readwrite'),s=t.objectStore('base');const op=action==='get'?s.get(originalToken):action==='delete'?s.delete(originalToken):s.put(value,originalToken);op.onsuccess=()=>{if(action==='get')resolve(op.result)};t.oncomplete=()=>{d.close();if(action!=='get')resolve(true)};t.onerror=()=>reject(t.error)}})}
async function importFile(file){if(!file)return;if(!/\.(xlsx|csv)$/i.test(file.name))return $('importStatus').textContent='Selecione um arquivo .xlsx ou .csv.';if(file.size>40*1024*1024)return $('importStatus').textContent='Arquivo acima de 40 MB. Divida a base e tente novamente.';$('importStatus').textContent='Lendo todas as abas. Aguarde…';$('fileInput').disabled=true;try{const parsed=await ExcelIO.read(file);if(!parsed.sheets.length||!parsed.sheets.some(s=>s.rows.length>1))throw Error('Nenhum registro de dados encontrado.');const match=file.name.match(/(\d{2})[-_](\d{2})[-_](\d{4})/);book={name:file.name,reference:match?`${match[1]}/${match[2]}/${match[3]}`:'não informada no nome do arquivo',importedAt:new Date().toISOString(),sheets:parsed.sheets};original=parsed.bytes?toBase64(parsed.bytes):'';setup();$('storageState').textContent='Base importada neste navegador';try{await db('put',{book,original});$('storageState').textContent='Base importada • salva neste navegador'}catch{$('storageState').textContent='Base importada • válida nesta sessão';toast('A base foi carregada, mas o navegador não permitiu salvá-la. Exporte antes de fechar.')}$('importStatus').textContent=`Importação concluída: ${book.sheets.length} abas e ${int(base.length)} registros na base de indicadores.`;toast('Nova base carregada com sucesso.')}catch(e){$('importStatus').textContent='Não foi possível importar: '+e.message}finally{$('fileInput').disabled=false;$('fileInput').value=''}}
for(const id of filterIds)$(id).addEventListener('change',refresh);for(const id of ['dateFrom','dateTo'])$(id).addEventListener('change',refresh);let debounce;$('globalSearch').addEventListener('input',()=>{clearTimeout(debounce);debounce=setTimeout(refresh,180)});$('clearFilters').onclick=()=>{for(const id of [...filterIds,'dateFrom','dateTo','globalSearch'])$(id).value='';refresh()};
$('sheetTabs').onclick=e=>{const b=e.target.closest('[data-sheet]');if(b)setSheet(Number(b.dataset.sheet))};$('tableWrap').onclick=e=>{const b=e.target.closest('[data-sort]');if(b){const c=Number(b.dataset.sort);sortDir=c===sortCol?-sortDir:1;sortCol=c;renderTable()}const cell=e.target.closest('[data-detail]');if(cell)detail(Number(cell.dataset.detail))};$('tableWrap').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-detail]')){e.preventDefault();detail(Number(e.target.dataset.detail))}};
for(const id of ['sheetSearch','columnValue'])$(id).oninput=()=>{page=0;renderTable()};for(const id of ['columnFilter','applyGlobal','pageSize'])$(id).onchange=()=>{page=0;renderTable()};$('prevPage').onclick=()=>{page--;renderTable()};$('nextPage').onclick=()=>{page++;renderTable()};
$('contractorChart').onclick=e=>{const el=e.target.closest('[data-contractor]');if(el){$('contractor').value=el.dataset.contractor;refresh()}};$('trend').onclick=e=>{const el=e.target.closest('[data-month]');if(el){const m=el.dataset.month;$('dateFrom').value=m+'-01';const [y,n]=m.split('-').map(Number);$('dateTo').value=new Date(Date.UTC(y,n,0)).toISOString().slice(0,10);refresh()}};
for(const id of ['exportOpen','tableExport'])$(id).onclick=()=>$('exportDialog').showModal();for(const id of ['importOpen','navImport'])$(id).onclick=()=>$('importDialog').showModal();$('fileInput').onchange=e=>importFile(e.target.files[0]);$('exportFull').onclick=()=>fullExport().catch(e=>toast(e.message));$('exportXlsx').onclick=()=>exportQuery('xlsx').catch(e=>toast(e.message));$('exportCsv').onclick=()=>exportQuery('csv').catch(e=>toast(e.message));$('exportPublish').onclick=()=>{download(new Blob(['window.FCU_INITIAL='+JSON.stringify(book)+';\nwindow.FCU_ORIGINAL='+JSON.stringify(original)+';'],{type:'text/javascript;charset=utf-8'}),'data.js');toast('data.js exportado. Substitua esse arquivo no GitHub para compartilhar a atualização.')};
$('restoreBase').onclick=async()=>{book=window.FCU_INITIAL;original=window.FCU_ORIGINAL;try{await db('delete')}catch{}setup();$('storageState').textContent='Base incluída no site';$('importStatus').textContent='Base original restaurada.';toast('Base incluída no site restaurada.')};
function tick(){const d=new Date();$('clock').textContent=d.toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo'});$('today').textContent=d.toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'});$('clock').dateTime=d.toISOString()}tick();setInterval(tick,1000);setup();db('get').then(saved=>{if(saved?.book){book=saved.book;original=saved.original;setup();$('storageState').textContent='Base importada • salva neste navegador'}}).catch(()=>{});
window.FCU_TEST={get:()=>({book,base,filtered,selected,tableRows,matchedProjects}),dateISO,display};

}).catch(e=>{console.error(e);document.body.innerHTML='<main style="font-family:Arial,sans-serif;padding:32px"><h1>Não foi possível carregar a base FCU.</h1><p>Atualize a página. Se o problema persistir, verifique a publicação do arquivo de dados.</p></main>';});
